create table if not exists outbox_events (
    id bigint generated by default as identity primary key,
    aggregate_type varchar(100) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(100) not null,
    payload varchar(2000) not null,
    status varchar(50) not null
);
