import { type Issue } from "@/lib/types";

function activity(id: string, message: string, timestamp: string) {
  return {
    id,
    type: "created" as const,
    actor: "Ops seed",
    message,
    timestamp,
  };
}

export function createSeedIssues(): Issue[] {
  return [
    {
      id: "OPS-101",
      title: "Checkout retries spike after wallet fallback",
      summary: "Enterprise tenants report duplicate attempts and failed fallback payments.",
      customer: "Northwind Health",
      source: "monitoring",
      status: "investigating",
      priority: "p0",
      slaRisk: "breach",
      labels: ["checkout", "billing", "latency"],
      routeTeam: "payments",
      owner: "Mina Park",
      accountTier: "enterprise",
      affectedUsers: 1840,
      createdAt: "2026-03-07T01:20:00.000Z",
      updatedAt: "2026-03-07T09:30:00.000Z",
      lastSeenAt: "2026-03-07T09:32:00.000Z",
      operatorNote: "Partner PSP rollback is under review.",
      activity: [
        activity("OPS-101-a1", "Monitoring created the incident.", "2026-03-07T01:20:00.000Z"),
      ],
    },
    {
      id: "OPS-102",
      title: "Search results disappear after filter reset",
      summary: "Feedback cluster shows empty states for retained search journeys.",
      customer: "BrightCart",
      source: "feedback",
      status: "untriaged",
      priority: "p2",
      slaRisk: "watch",
      labels: ["search", "retention"],
      routeTeam: "growth",
      owner: "Mina Park",
      accountTier: "growth",
      affectedUsers: 320,
      createdAt: "2026-03-06T21:05:00.000Z",
      updatedAt: "2026-03-07T08:42:00.000Z",
      lastSeenAt: "2026-03-07T08:44:00.000Z",
      operatorNote: "",
      activity: [
        activity("OPS-102-a1", "Feedback ingestion created the issue.", "2026-03-06T21:05:00.000Z"),
      ],
    },
    {
      id: "OPS-103",
      title: "Mobile billing modal traps focus on Safari",
      summary: "Support escalated repeated keyboard trap reports from tablet users.",
      customer: "Canvas Lane",
      source: "support",
      status: "monitoring",
      priority: "p1",
      slaRisk: "watch",
      labels: ["billing", "mobile"],
      routeTeam: "product",
      owner: "Mina Park",
      accountTier: "growth",
      affectedUsers: 122,
      createdAt: "2026-03-06T15:10:00.000Z",
      updatedAt: "2026-03-07T07:10:00.000Z",
      lastSeenAt: "2026-03-07T07:40:00.000Z",
      operatorNote: "Waiting for patch verification on iPadOS.",
      activity: [
        activity("OPS-103-a1", "Support escalated an accessibility bug.", "2026-03-06T15:10:00.000Z"),
      ],
    },
    {
      id: "OPS-104",
      title: "QA regression on invoice export permissions",
      summary: "Download CTA remains enabled for viewers after permission downgrade.",
      customer: "Internal QA",
      source: "qa",
      status: "escalated",
      priority: "p1",
      slaRisk: "breach",
      labels: ["billing"],
      routeTeam: "platform",
      owner: "Mina Park",
      accountTier: "enterprise",
      affectedUsers: 42,
      createdAt: "2026-03-06T10:00:00.000Z",
      updatedAt: "2026-03-07T09:10:00.000Z",
      lastSeenAt: "2026-03-07T09:15:00.000Z",
      operatorNote: "Security review requested before hotfix.",
      activity: [
        activity("OPS-104-a1", "QA suite detected a permission regression.", "2026-03-06T10:00:00.000Z"),
      ],
    },
    {
      id: "OPS-105",
      title: "Latency alert on saved views API",
      summary: "Monitoring shows response times above 2.2s on enterprise workspaces.",
      customer: "Harvest Loop",
      source: "monitoring",
      status: "investigating",
      priority: "p1",
      slaRisk: "breach",
      labels: ["latency", "search"],
      routeTeam: "platform",
      owner: "Mina Park",
      accountTier: "enterprise",
      affectedUsers: 870,
      createdAt: "2026-03-07T03:48:00.000Z",
      updatedAt: "2026-03-07T09:28:00.000Z",
      lastSeenAt: "2026-03-07T09:33:00.000Z",
      operatorNote: "",
      activity: [
        activity("OPS-105-a1", "APM alert opened the issue.", "2026-03-07T03:48:00.000Z"),
      ],
    },
    {
      id: "OPS-106",
      title: "Feedback inbox tags save twice on fast submit",
      summary: "Operators see duplicate tags after rapid triage.",
      customer: "Nimble CX",
      source: "feedback",
      status: "untriaged",
      priority: "p2",
      slaRisk: "healthy",
      labels: ["retention"],
      routeTeam: "product",
      owner: "Mina Park",
      accountTier: "starter",
      affectedUsers: 88,
      createdAt: "2026-03-05T23:14:00.000Z",
      updatedAt: "2026-03-07T06:20:00.000Z",
      lastSeenAt: "2026-03-07T06:21:00.000Z",
      operatorNote: "",
      activity: [
        activity("OPS-106-a1", "Feedback workflow created the issue.", "2026-03-05T23:14:00.000Z"),
      ],
    },
    {
      id: "OPS-107",
      title: "Support macro routes incidents to wrong queue",
      summary: "Triage macros point payment incidents into the product backlog.",
      customer: "Southbay Transit",
      source: "support",
      status: "investigating",
      priority: "p2",
      slaRisk: "watch",
      labels: ["billing"],
      routeTeam: "support",
      owner: "Mina Park",
      accountTier: "growth",
      affectedUsers: 63,
      createdAt: "2026-03-06T19:40:00.000Z",
      updatedAt: "2026-03-07T05:55:00.000Z",
      lastSeenAt: "2026-03-07T06:12:00.000Z",
      operatorNote: "Macro mapping updated, waiting for fresh support tickets.",
      activity: [
        activity("OPS-107-a1", "Support macro issue created.", "2026-03-06T19:40:00.000Z"),
      ],
    },
    {
      id: "OPS-108",
      title: "Monitoring noise on stale mobile sessions",
      summary: "Alert volume is high but user impact is low after session timeout changes.",
      customer: "Observability",
      source: "monitoring",
      status: "monitoring",
      priority: "p3",
      slaRisk: "healthy",
      labels: ["mobile"],
      routeTeam: "platform",
      owner: "Mina Park",
      accountTier: "starter",
      affectedUsers: 12,
      createdAt: "2026-03-05T14:25:00.000Z",
      updatedAt: "2026-03-07T04:15:00.000Z",
      lastSeenAt: "2026-03-07T04:20:00.000Z",
      operatorNote: "Can probably downgrade after the next release.",
      activity: [
        activity("OPS-108-a1", "Monitoring alert opened as low severity.", "2026-03-05T14:25:00.000Z"),
      ],
    },
    {
      id: "OPS-109",
      title: "Search facet order resets after refresh",
      summary: "Operators lose custom queue sort when switching between saved views.",
      customer: "Northwind Health",
      source: "qa",
      status: "resolved",
      priority: "p2",
      slaRisk: "healthy",
      labels: ["search"],
      routeTeam: "growth",
      owner: "Mina Park",
      accountTier: "enterprise",
      affectedUsers: 40,
      createdAt: "2026-03-05T09:10:00.000Z",
      updatedAt: "2026-03-06T23:10:00.000Z",
      lastSeenAt: "2026-03-06T23:30:00.000Z",
      operatorNote: "Resolved in release 24.3.7.",
      activity: [
        activity("OPS-109-a1", "QA found sort reset on refresh.", "2026-03-05T09:10:00.000Z"),
      ],
    },
    {
      id: "OPS-110",
      title: "Retention cohort export misses weekend sessions",
      summary: "Growth teams see a gap in Sunday event ingestion for one segment.",
      customer: "BrightCart",
      source: "feedback",
      status: "untriaged",
      priority: "p3",
      slaRisk: "healthy",
      labels: ["retention"],
      routeTeam: "growth",
      owner: "Mina Park",
      accountTier: "growth",
      affectedUsers: 19,
      createdAt: "2026-03-06T04:22:00.000Z",
      updatedAt: "2026-03-07T03:15:00.000Z",
      lastSeenAt: "2026-03-07T03:18:00.000Z",
      operatorNote: "",
      activity: [
        activity("OPS-110-a1", "Customer feedback imported from weekly review.", "2026-03-06T04:22:00.000Z"),
      ],
    },
    {
      id: "OPS-111",
      title: "Escalation policy sends VIP outages to growth",
      summary: "Enterprise monitoring incidents are landing in the wrong owning team.",
      customer: "Skyline Payroll",
      source: "support",
      status: "escalated",
      priority: "p0",
      slaRisk: "breach",
      labels: ["billing", "latency"],
      routeTeam: "support",
      owner: "Mina Park",
      accountTier: "enterprise",
      affectedUsers: 980,
      createdAt: "2026-03-07T00:22:00.000Z",
      updatedAt: "2026-03-07T09:18:00.000Z",
      lastSeenAt: "2026-03-07T09:31:00.000Z",
      operatorNote: "Needs policy update and routing audit.",
      activity: [
        activity("OPS-111-a1", "Support manager escalated routing mismatch.", "2026-03-07T00:22:00.000Z"),
      ],
    },
    {
      id: "OPS-112",
      title: "Mobile queue loses scroll when detail closes",
      summary: "Tablet triage flow jumps back to the top after note submission.",
      customer: "FieldWorks",
      source: "qa",
      status: "investigating",
      priority: "p2",
      slaRisk: "watch",
      labels: ["mobile", "search"],
      routeTeam: "product",
      owner: "Mina Park",
      accountTier: "growth",
      affectedUsers: 76,
      createdAt: "2026-03-06T12:12:00.000Z",
      updatedAt: "2026-03-07T08:05:00.000Z",
      lastSeenAt: "2026-03-07T08:06:00.000Z",
      operatorNote: "Likely focus restore bug in detail drawer.",
      activity: [
        activity("OPS-112-a1", "QA reproduced scroll reset on iPad layout.", "2026-03-06T12:12:00.000Z"),
      ],
    },
  ];
}

