create table if not exists commerce_products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    price numeric(12, 2) not null,
    stock integer not null,
    version bigint not null default 0
);

create table if not exists commerce_cart_items (
    id bigint generated by default as identity primary key,
    customer_email varchar(255) not null,
    product_id bigint not null,
    quantity integer not null
);

create table if not exists commerce_orders (
    id bigint generated by default as identity primary key,
    customer_email varchar(255) not null,
    total_quantity integer not null,
    status varchar(50) not null
);
