create table if not exists users (
    id varchar(64) primary key,
    email varchar(255) not null unique,
    password_hash varchar(255),
    display_name varchar(255) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null
);

create table if not exists user_roles (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null,
    role_name varchar(50) not null,
    created_at timestamp with time zone not null,
    constraint fk_user_roles_user foreign key (user_id) references users(id),
    constraint uq_user_roles_user_role unique (user_id, role_name)
);

create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    token_hash varchar(128) not null unique,
    user_id varchar(64) not null,
    csrf_token varchar(128) not null,
    expires_at timestamp with time zone not null,
    revoked boolean not null default false,
    created_at timestamp with time zone not null,
    constraint fk_refresh_tokens_user foreign key (user_id) references users(id)
);

create table if not exists oauth_accounts (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null,
    provider varchar(50) not null,
    provider_subject varchar(255) not null,
    created_at timestamp with time zone not null,
    constraint fk_oauth_accounts_user foreign key (user_id) references users(id),
    constraint uq_oauth_accounts_provider_subject unique (provider, provider_subject)
);

create table if not exists audit_events (
    id bigint generated by default as identity primary key,
    event_type varchar(100) not null,
    user_id varchar(64),
    message varchar(500) not null,
    created_at timestamp with time zone not null
);

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    slug varchar(120) not null unique,
    active boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    category_id bigint not null,
    name varchar(255) not null,
    description varchar(1000) not null,
    price numeric(12, 2) not null,
    stock integer not null,
    active boolean not null default true,
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_products_category foreign key (category_id) references categories(id)
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null,
    status varchar(50) not null,
    total_amount numeric(12, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_orders_user foreign key (user_id) references users(id)
);

create table if not exists order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_name_snapshot varchar(255) not null,
    unit_price numeric(12, 2) not null,
    quantity integer not null,
    line_total numeric(12, 2) not null,
    created_at timestamp with time zone not null,
    constraint fk_order_items_order foreign key (order_id) references orders(id),
    constraint fk_order_items_product foreign key (product_id) references products(id)
);

create table if not exists inventory_reservations (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    status varchar(50) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_inventory_reservations_order foreign key (order_id) references orders(id),
    constraint fk_inventory_reservations_product foreign key (product_id) references products(id)
);

create table if not exists payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique,
    idempotency_key varchar(255) not null unique,
    provider varchar(50) not null,
    status varchar(50) not null,
    amount numeric(12, 2) not null,
    created_at timestamp with time zone not null,
    confirmed_at timestamp with time zone,
    constraint fk_payments_order foreign key (order_id) references orders(id)
);

create table if not exists outbox_events (
    id bigint generated by default as identity primary key,
    aggregate_type varchar(80) not null,
    aggregate_id varchar(120) not null,
    event_type varchar(120) not null,
    payload varchar(4000) not null,
    created_at timestamp with time zone not null,
    published_at timestamp with time zone
);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null,
    type varchar(80) not null,
    message varchar(500) not null,
    dedup_key varchar(255) not null unique,
    created_at timestamp with time zone not null,
    constraint fk_notifications_user foreign key (user_id) references users(id)
);

