.PHONY: install test typecheck clean

install:
	cd ../../../.. && npm install

test:
	cd ../../../.. && npm run test:vdom

typecheck:
	cd ../../../.. && npm run typecheck:vdom

clean:
	cd ../../../.. && rm -rf node_modules

