services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    ports:
      - "${SERVER_PORT:-8111}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mailpit:
        condition: service_started
      redpanda:
        condition: service_started

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-commerce_backend_v2}
      POSTGRES_USER: ${POSTGRES_USER:-study2}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-study2}
    ports:
      - "${POSTGRES_PORT:-5551}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-study2} -d ${POSTGRES_DB:-commerce_backend_v2}"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6391}:6379"

  mailpit:
    image: axllent/mailpit:v1.24
    ports:
      - "${MAILPIT_SMTP_PORT:-1031}:1025"
      - "${MAILPIT_UI_PORT:-8130}:8025"

  redpanda:
    image: redpandadata/redpanda:v24.3.8
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      - --advertise-kafka-addr
      - INTERNAL://redpanda:9092,EXTERNAL://localhost:${KAFKA_PORT:-19091}
    ports:
      - "${KAFKA_PORT:-19091}:19092"
