apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-backend.fullname" . }}
  labels:
    {{- include "go-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_SSLMODE: {{ .Values.database.sslmode | quote }}
