create table if not exists lab_products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    price numeric(12, 2) not null,
    version bigint not null default 0
);
